# Application Name
spring.application.name=crypto-price-aggregator

# Server Configuration
server.port=8080

# Logging Configuration
logging.level.com.cryptoArb.crypto_price_aggregator=DEBUG
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - [%thread] %-5level %logger{36} - %msg%n

# Actuator (if enabled later)
management.endpoints.web.exposure.include=health,info
