package com.cryptoArb.repository;

import com.cryptoArb.domain_spring.ArbitrageOpportunity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.util.List;

/**
 * Spring Data JPA repository for the ArbitrageOpportunity entity.
 *
 * By extending JpaRepository, we get a full set of CRUD methods
 * (save, findById, findAll, delete, etc.) for free.
 */
@Repository
public interface ArbitrageRepository extends JpaRepository<ArbitrageOpportunity, Long> {

    /**
     * Finds opportunities detected after a specific timestamp.
     * This is used to filter for "recent" events (e.g., last 24 hours).
     *
     * @param timestamp The cutoff time.
     * @return A list of opportunities found after that time.
     * <p>
     * for example :
     * <p>
     * findByTimestampAfter(Instant.now().minus(24, ChronoUnit.HOURS))
     * <p>
     * will return all opportunities detected in the last 24 hours.
     * <p>
     * the SQL query generated by Spring Data JPA will be:
     * <p>
     * SELECT * FROM arbitrage_opportunity WHERE timestamp > ?
     * <p>
     * the ? is a placeholder for the timestamp parameter.
     */
    List<ArbitrageOpportunity> findByTimestampAfter(Instant timestamp);
}
